scrape_configs:
  - job_name: 'user_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
      - targets: ['host.docker.internal:8082']
      - targets: ['host.docker.internal:8083']
      - targets: ['host.docker.internal:8084']
      - targets: ['host.docker.internal:8085']
      - targets: ['host.docker.internal:8086']
