server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: Postgres17@ukg
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  secret: my-secret-key-for-jwt-is-1234567!@#
  expiration: 600000

admin:
  secret:
    code: ADMIN-secret-code-is-admin12345!@#
